### ISSUE TITLE
Странные ошибки

### ISSUE THREAD

**Issue by ruzen42** [Kamilayza/VisObsiTag#1]
![Screenshot at 2024-12-12 15-15-32](https://github.com/user-attachments/assets/0dc4f9d0-61b5-478a-9da0-26cdf91b5d47)
на работу проги это не влияет, но странновато

**Comment by Kamilayza** [comment]
Исправила в одном скрипте криво написанное имя файла. 
Ошибки должны быть исправлены. 
Спасибо, что тестируете этот пока ещё сырой проект.
